# Generated by Django 3.2.7 on 2022-01-04 13:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_postcontent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Postcontent',
        ),
    ]
