# Generated by Django 3.2.7 on 2021-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20211214_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
