# Generated by Django 3.2.7 on 2021-12-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20211216_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_images',
            new_name='Blog_image',
        ),
    ]
