# Generated by Django 3.2.7 on 2022-01-01 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_blog_images_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='head',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
