# Generated by Django 3.2.7 on 2022-01-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_blogpost_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_image',
        ),
    ]
