# Generated by Django 3.2.7 on 2021-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backimages',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
