# Generated by Django 3.2.7 on 2021-11-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_backimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(default=0, max_length=5),
        ),
    ]
