# Generated by Django 3.2.7 on 2021-12-04 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='none', max_length=500)),
                ('size', models.CharField(default='S', max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('Hostel_name', models.CharField(max_length=500)),
                ('Unit', models.CharField(max_length=4)),
                ('City', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
