# Generated by Django 3.2.7 on 2021-12-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_address_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='price',
        ),
    ]
